version: "3"

services:
  api:
    image: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/golang-builder-image:1.13
    depends_on:
      - classifier
    build:
      context: go/docker/builder
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor
    volumes:
      - ./go/classifier:/go/src/github.com/ustrugany/classifier
    working_dir: /go/src/github.com/ustrugany/classifier
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go", "--server_addr=classifier:7771"]
  elasticsearch:
    image: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/elasticsearch-mediumdump
  classifier:
    build:
      context: python
    environment:
      - S3_MODELS_REGION=eu-west-1
      - S3_MODELS_BUCKET=manager-classifier2
      - S3_MODELS_SECRET_KEY=Odx2qY5M6EqPDNRzYSt+cyuhgOZbMNUy1Z0otF2e
      - S3_MODELS_ACCESS_KEY=AKIAURB4OY5SOGIFG7UG
      - TORCH_HOME=/app/.cache
    volumes:
      - ./classifier/app:/app
      - ./input:/app/input
    ports:
      - "7771:7771"
    command: ["python", "classifier_server.py", "[::]:7771"]
#  api:
#    depends_on:
#      - classifier
#    build:
#      context: go/app
#      args:
#        - GITHUB_TOKEN=${GITHUB_TOKEN}
#    environment:
#      - CGO_ENABLED=0
#      - GO111MODULE=on
#      - GOFLAGS=-mod=vendor
#    volumes:
#      - ./api/app:/app
#      - ./input:/app/input
#    ports:
#      - "8080:8080"
#    command: ["go", "run", "main.go", "--server_addr=classifier:7771"]
