import os

S3_MODELS_ACCESS_KEY = os.environ["S3_MODELS_ACCESS_KEY"]
S3_MODELS_SECRET_KEY = os.environ["S3_MODELS_SECRET_KEY"]
S3_MODELS_BUCKET = os.environ["S3_MODELS_BUCKET"]
S3_MODELS_REGION = os.environ["S3_MODELS_REGION"]
